# Generated by Django 4.2.1 on 2023-07-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_games_developername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='developerName',
            field=models.TextField(default='Add Developer Name', max_length=50, null=True),
        ),
    ]
