# Generated by Django 4.2.1 on 2023-07-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_alter_games_developername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='developerName',
            field=models.CharField(max_length=50),
        ),
    ]
