# Generated by Django 4.2.1 on 2023-07-24 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_games_img_1_games_img_2_games_img_3_games_img_cover_and_more'),
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='game',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='games.games'),
        ),
    ]
