# Generated by Django 4.2.1 on 2023-06-21 18:40

from django.db import migrations, models
import django.db.models.deletion
import games.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gameCount', models.IntegerField()),
                ('email', models.EmailField(max_length=254, verbose_name='Contact Email')),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('release_date', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('requirements', models.TextField(validators=[games.models.sysreqCheck])),
                ('price', models.FloatField()),
                ('publisherName', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='games.publisher')),
            ],
        ),
    ]
