# Generated by Django 4.2.1 on 2023-07-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='developerName',
            field=models.TextField(default=None, max_length=50),
        ),
    ]
