# Generated by Django 4.2.1 on 2023-07-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_alter_games_developername'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='img_1',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%y/%m/%d', verbose_name='Trailer Image 1'),
        ),
        migrations.AddField(
            model_name='games',
            name='img_2',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%y/%m/%d', verbose_name='Trailer Image 2'),
        ),
        migrations.AddField(
            model_name='games',
            name='img_3',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%y/%m/%d', verbose_name='Trailer Image 3'),
        ),
        migrations.AddField(
            model_name='games',
            name='img_cover',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%y/%m/%d', verbose_name='Splash Art'),
        ),
        migrations.AddField(
            model_name='games',
            name='trailer',
            field=models.FileField(blank=True, null=True, upload_to='videos/%y/%m/%d', verbose_name='Video Trailer'),
        ),
    ]
