# Generated by Django 4.2.4 on 2023-08-21 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_games_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='reviews',
        ),
    ]
