# Generated by Django 4.2.1 on 2023-07-02 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_isstaff_user_is_staff_remove_user_issuperuser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='name',
        ),
    ]
