# Generated by Django 4.2.1 on 2023-07-02 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_username_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='isActive',
            new_name='is_active',
        ),
    ]
